# Generated by Django 4.0.4 on 2022-04-25 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_profile_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectname',
            name='faculty',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='timetable.faculty'),
        ),
    ]
