# Generated by Django 4.0.4 on 2022-04-25 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0005_subjectname_faculty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectname',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='subjectname',
            name='faculty',
        ),
        migrations.AddField(
            model_name='subjectname',
            name='groups',
            field=models.ManyToManyField(to='timetable.group'),
        ),
    ]
